version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guess
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - database
    expose:
      - 5432

  backend-0:
    build: ./
    depends_on:
      - postgres
    environment:
      FLASK_APP: run.py
      FLASK_DB_TYPE: postgres
      FLASK_DB_USER: user
      FLASK_DB_NAME: guess
      FLASK_DB_PASSWORD: password
      FLASK_DB_HOST: postgres
      FLASK_DB_PORT: 5432
    restart: always
    expose:
      - 5000
    ports:
      - 5000:5000
    networks:
      - webnet
      - database

  backend-1:
    build: ./
    depends_on:
      - postgres
    environment:
      FLASK_APP: run.py
      FLASK_DB_TYPE: postgres
      FLASK_DB_USER: user
      FLASK_DB_NAME: guess
      FLASK_DB_PASSWORD: password
      FLASK_DB_HOST: postgres
      FLASK_DB_PORT: 5432
    restart: always
    expose:
      - 5000
    ports:
      - 5001:5000
    networks:
      - webnet
      - database

  frontend:
    build: ./frontend
    environment:
      REACT_APP_BACKEND_URL: /api
    restart: always
    networks:
      - webnet
    expose:
      - 3000
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - frontend
    restart: always
    networks:
      - webnet

volumes:
  postgres_data:

networks:
  webnet:
  database: